version: '3'
services:
  go-api:
    container_name: go-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    restart: unless-stopped
    networks:
      - go-api-network
    environment:
      API_PORT: 5555
      DATABASE_HOST: go-store
      DATABASE_PORT: 5432
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: hrtools
      GIN_MODE: release
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: ${GOOSE_DRIVER}://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    ports:
      - 5555:5555
    depends_on:
      - db

  db:
    container_name: go-api-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: hrtools
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - go-api-network

volumes:
  postgres:


networks:
  go-api-network:
    driver: bridge
