definitions:
  healthCheckController.HealthCheck:
    properties:
      message:
        example: Server running!
        type: string
    type: object
  models.HelloWorldBodyInput:
    description: Basic information to create a new entity
    properties:
      name:
        example: Jonathan Doe
        maxLength: 40
        minLength: 1
        type: string
    required:
    - name
    type: object
  models.HelloWorldPresenter:
    properties:
      id:
        example: ea68c913-2e60-487d-b108-26836271e500
        type: string
      name:
        example: jon doe
        type: string
    type: object
host: localhost:1337
info:
  contact:
    email: augusto.timm@gmail.com
    name: Augusto Timm
    url: https://github.com/augustotimm
  description: A complete boilerplate in golang using gin framework
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Backend BoilerPlate
  version: "1.0"
paths:
  /health-check:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/healthCheckController.HealthCheck'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Shows information if api is running
  /hello-world:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.HelloWorldPresenter'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Simple list data example
    post:
      consumes:
      - application/json
      parameters:
      - description: Input data to create new entity
        in: body
        name: hw
        required: true
        schema:
          $ref: '#/definitions/models.HelloWorldBodyInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            type: Object
      summary: Simple Create entity example
swagger: "2.0"
